---
- hosts: all
  vars:
    RHEL_ROOT_PASSWORD: "{{ root_password }}"
 
  tasks:
    - name: Checking for Required Variables
      fail: msg="Variable '{{ item }}' is not defined"
      when: "{{ item }} is not defined"
      with_items: "{{ RHEL_ROOT_PASSWORD }}"
 
    - name: Change root password
      user: name=root password="{{ RHEL_ROOT_PASSWORD }}"
